# Generated by Django 5.2.8 on 2025-11-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
