# Generated by Django 5.2.8 on 2025-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppinglistitem_mealplan_in_shopping_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='no_need_to_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='dont_need',
            field=models.BooleanField(default=False),
        ),
    ]
