# Generated by Django 5.2.8 on 2025-11-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_activeshoppingitem_shoppinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('added_to_list', 'Added to List'), ('in_shopping', 'In Shopping'), ('shopped', 'Shopped')], default='planned', max_length=20),
        ),
    ]
